begin;
-- Fixtures exist only in this transaction and are always rolled back.
do $$
declare u1 uuid:=gen_random_uuid();u2 uuid:=gen_random_uuid();ad uuid:=gen_random_uuid();cv uuid;cid uuid;sid uuid;q1 uuid;q2 uuid;req uuid:=gen_random_uuid();r jsonb; n integer;
begin
 insert into auth.users(id,email,email_confirmed_at) values(u1,'academic-test-1@example.invalid',now()),(u2,'academic-test-2@example.invalid',now()),(ad,'academic-admin@example.invalid',now());
 insert into public.tipix_student_profiles(id,full_name,school_name,school_city,grade,stream) values(u1,'Student One','Test School','Test City',12,'pcm'),(u2,'Student Two','Test School','Test City',12,'pcm'),(ad,'Admin Test','Test School','Test City',12,'pcm');
 insert into tipix_private.academic_staff values(ad,'admin');
 insert into public.academic_curriculum_versions(board,academic_year,class_level,subject,official_source,status) values('TEST','2026-27',12,'Mathematics','https://example.invalid/syllabus','published') returning id into cv;
 insert into public.academic_concepts(curriculum_id,chapter_title,concept_title,published) values(cv,'Test chapter','Test concept',true) returning id into cid;
 insert into public.academic_source_registry(source_code,source_name,source_type,organization,base_url,rights_status,license_code,rights_reference,active) values('rollback-test','TEST ONLY','open','Fixture','https://example.invalid','approved','test-only','Rollback fixtures only',true) returning id into sid;
 perform set_config('request.jwt.claim.sub',ad::text,true);
 execute 'set local role authenticated';
 r:=public.academic_api('import_question',jsonb_build_object('source_id',sid,'concept_id',cid,'question_type','mcq','question_text','Rollback fixture one','options',jsonb_build_array('A','B'),'answer',0,'source_url','https://example.invalid/q1','rights_reference','Test fixture only','license_code','test'));
 q1:=(r->>'id')::uuid;perform public.academic_api('publish_question',jsonb_build_object('question_id',q1));
 r:=public.academic_api('import_question',jsonb_build_object('source_id',sid,'concept_id',cid,'question_type','mcq','question_text','Rollback fixture two','options',jsonb_build_array('A','B'),'answer',1,'source_url','https://example.invalid/q2','rights_reference','Test fixture only','license_code','test'));
 q2:=(r->>'id')::uuid;perform public.academic_api('publish_question',jsonb_build_object('question_id',q2));
 perform set_config('request.jwt.claim.sub',u1::text,true);
 begin perform public.academic_api('admin_review');raise exception 'FAIL: student accessed admin';exception when insufficient_privilege then null;end;
 begin perform * from tipix_private.academic_answer_keys;raise exception 'FAIL: answer keys readable';exception when insufficient_privilege then null;end;
 begin perform public.academic_api('review',jsonb_build_object('question_id',q1));raise exception 'FAIL: answer leaked before submission';exception when insufficient_privilege then null;end;
 r:=public.academic_api('next',jsonb_build_object('concept_id',cid));
 if r->'question' ? 'answer' then raise exception 'FAIL: answer key in question response';end if;
 r:=public.academic_api('submit',jsonb_build_object('question_id',q1,'request_id',req,'answer',0));
 if (r->'attempt'->>'points')::integer<>10 then raise exception 'FAIL: correct score';end if;
 perform public.academic_api('submit',jsonb_build_object('question_id',q1,'request_id',req,'answer',0));
 perform public.academic_api('submit',jsonb_build_object('question_id',q1,'request_id',gen_random_uuid(),'answer',0));
 select count(*) into n from public.academic_attempts;if n<>1 then raise exception 'FAIL: duplicate writes';end if;
 r:=public.academic_api('next',jsonb_build_object('concept_id',cid));if r->'question'->>'id'<>q2::text then raise exception 'FAIL: resume';end if;
 r:=public.academic_api('submit',jsonb_build_object('question_id',q2,'request_id',gen_random_uuid(),'answer',0));if (r->'attempt'->>'correct')::boolean then raise exception 'FAIL: wrong answer';end if;
 select count(*) into n from public.academic_mistake_memory;if n<>1 then raise exception 'FAIL: mistake missing';end if;
 r:=public.academic_api('submit',jsonb_build_object('question_id',q2,'request_id',gen_random_uuid(),'answer',1,'retry',true));if (r->'attempt'->>'points')::integer<>0 then raise exception 'FAIL: retry points';end if;
 if exists(select 1 from public.academic_mistake_memory where resolved_at is null) then raise exception 'FAIL: recovery missing';end if;
 r:=public.academic_api('overview');if (r->'totals'->>'points')::integer<>10 or (r->'totals'->>'attempted')::integer<>2 then raise exception 'FAIL: totals';end if;
 if (r->'concepts'->0->>'mastery') is not null then raise exception 'FAIL: insufficient evidence';end if;
 perform public.academic_api('goal','{"exam":"JEE Main","target_score":200}');
 perform set_config('request.jwt.claim.sub',u2::text,true);
 select count(*) into n from public.academic_attempts;if n<>0 then raise exception 'FAIL: RLS cross-student attempt';end if;
 select count(*) into n from public.academic_goals;if n<>0 then raise exception 'FAIL: RLS cross-student goal';end if;
 begin insert into public.academic_attempts(student_id,question_id,request_id,selected_answer,correct,marks_earned,marks_available,attempt_number,response_time_ms) values(u2,q1,gen_random_uuid(),'0',true,100,100,1,0);raise exception 'FAIL: client scoring write';exception when insufficient_privilege then null;end;
 r:=public.academic_api('next',jsonb_build_object('concept_id',cid));if r->'question' is null then raise exception 'FAIL: second student resume isolation';end if;
 execute 'reset role';
 update tipix_private.academic_staff set role='teacher' where user_id=ad;
 insert into tipix_private.academic_teacher_students values(ad,u1);
 perform set_config('request.jwt.claim.sub',ad::text,true);
 execute 'set local role authenticated';
 r:=public.academic_api('staff_report');if jsonb_array_length(r)<>1 or r->0->>'id'<>u1::text then raise exception 'FAIL: teacher scope';end if;
 begin perform public.academic_api('intervene',jsonb_build_object('student_id',u2,'message','Unauthorised action'));raise exception 'FAIL: teacher cross-student intervention';exception when insufficient_privilege then null;end;
 perform public.academic_api('intervene',jsonb_build_object('student_id',u1,'message','Review your recent concept mistakes'));
 execute 'reset role';
 update public.tipix_student_profiles set grade=10,stream=null where id=u2;
 perform set_config('request.jwt.claim.sub',u2::text,true);
 execute 'set local role authenticated';
 begin perform public.academic_api('next',jsonb_build_object('concept_id',cid));raise exception 'FAIL: wrong-grade access';exception when insufficient_privilege then null;end;
 execute 'reset role';
 update auth.users set email_confirmed_at=null where id=u2;
 execute 'set local role authenticated';
 begin perform public.academic_api('overview');raise exception 'FAIL: unverified account';exception when insufficient_privilege then null;end;
 execute 'reset role';
 if has_function_privilege('anon','public.academic_api(text,jsonb)','execute') then raise exception 'FAIL: anonymous API grant';end if;
 raise notice 'PASS: admin gate, private keys, before-submit feedback, scoring, idempotency, resume, mistakes, recovery, totals, evidence threshold, RLS isolation, direct-write denial';
end $$;
select 'passed' as academic_engine_assertions;
rollback;
