begin;
do $$
declare s1 uuid:=gen_random_uuid();s2 uuid:=gen_random_uuid();teacher uuid:=gen_random_uuid();cv uuid;cid uuid;src uuid;q1 uuid;q2 uuid;eid uuid;timed uuid;req uuid:=gen_random_uuid();r jsonb;first_score numeric;blocked boolean;
begin
 insert into auth.users(id,email,email_confirmed_at) values(s1,'exam-one@example.invalid',now()),(s2,'exam-two@example.invalid',now()),(teacher,'exam-teacher@example.invalid',now());
 insert into public.tipix_student_profiles(id,full_name,school_name,school_city,grade,stream) values(s1,'Exam One','Test School','Test City',12,'pcm'),(s2,'Exam Two','Test School','Test City',12,'pcm');
 insert into tipix_private.academic_staff values(teacher,'teacher');insert into tipix_private.academic_teacher_students values(teacher,s1);
 insert into public.academic_curriculum_versions(board,academic_year,class_level,subject,official_source,status) values('EXAM TEST','2099-00',12,'Mathematics','https://example.invalid','published') returning id into cv;
 insert into public.academic_concepts(curriculum_id,chapter_title,concept_title,published) values(cv,'Test chapter','Test concept',true) returning id into cid;
 insert into public.academic_source_registry(source_code,source_name,source_type,organization,base_url,rights_status,license_code,rights_reference,active) values('exam-rollback','Test source','open','Fixture','https://example.invalid','approved','fixture','Rollback only',true) returning id into src;
 insert into public.academic_verified_question_bank(concept_id,source_id,question_type,question_text,options,marks,negative_marks,source_url,license_code,rights_reference,fingerprint,is_verified,is_published,reviewed_by,reviewed_at) values(cid,src,'mcq','Exam fixture one','["A","B"]',4,1,'https://example.invalid','fixture','Rollback only','exam-one',true,true,teacher,now()) returning id into q1;
 insert into public.academic_verified_question_bank(concept_id,source_id,question_type,question_text,marks,negative_marks,source_url,license_code,rights_reference,fingerprint,is_verified,is_published,reviewed_by,reviewed_at) values(cid,src,'numerical','Exam fixture two',2,0,'https://example.invalid','fixture','Rollback only','exam-two',true,true,teacher,now()) returning id into q2;
 insert into tipix_private.academic_answer_keys values(q1,'0','Fixture explanation',0),(q2,'8','Fixture explanation',0.5);
 perform set_config('request.jwt.claim.sub',teacher::text,true);execute 'set local role authenticated';
 r:=public.exam_api('create',jsonb_build_object('concept_id',cid,'request_id',req,'title','Fixture assigned test','question_count',2,'duration_minutes',5,'closes_at',now()+interval '1 day','student_ids',jsonb_build_array(s1)));eid:=(r->>'id')::uuid;
 r:=public.exam_api('create',jsonb_build_object('concept_id',cid,'request_id',req,'title','Fixture assigned test','question_count',2,'duration_minutes',5,'closes_at',now()+interval '1 day','student_ids',jsonb_build_array(s1)));if r->>'id'<>eid::text then raise exception 'FAIL: duplicate exam';end if;
 blocked:=false;begin perform public.exam_api('create',jsonb_build_object('concept_id',cid,'request_id',gen_random_uuid(),'title','Unauthorised assignment','question_count',1,'duration_minutes',5,'closes_at',now()+interval '1 day','student_ids',jsonb_build_array(s2)));exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'FAIL: cross-teacher assignment';end if;
 blocked:=false;begin perform public.exam_api('release',jsonb_build_object('id',eid));exception when raise_exception then blocked:=true;end;if not blocked then raise exception 'FAIL: early release';end if;
 perform set_config('request.jwt.claim.sub',s2::text,true);
 blocked:=false;begin perform public.exam_api('start',jsonb_build_object('id',eid));exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'FAIL: unassigned start';end if;
 perform set_config('request.jwt.claim.sub',s1::text,true);
 blocked:=false;begin perform public.exam_api('options');exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'FAIL: student staff options';end if;
 r:=public.exam_api('start',jsonb_build_object('id',eid));if r->'review'<>'null'::jsonb or r->'score'<>'null'::jsonb or exists(select 1 from jsonb_array_elements(r->'questions')x where x ? 'answer') then raise exception 'FAIL: keys or score exposed';end if;
 r:=public.exam_api('save',jsonb_build_object('id',eid,'revision',1,'answers',jsonb_build_object(q1::text,0,q2::text,7.5)));
 if (r->>'revision')::integer<>1 then raise exception 'FAIL: revision';end if;
 r:=public.exam_api('start',jsonb_build_object('id',eid));if r->'answers'->q1::text<>'0'::jsonb then raise exception 'FAIL: resume';end if;
 blocked:=false;begin perform public.exam_api('save',jsonb_build_object('id',eid,'revision',1,'answers','{}'::jsonb));exception when raise_exception then blocked:=true;end;if not blocked then raise exception 'FAIL: stale save accepted';end if;
 blocked:=false;begin perform tipix_private.finish_exam(eid,s1);exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'FAIL: private grading callable';end if;
 r:=public.exam_api('submit',jsonb_build_object('id',eid));if r->'score'<>'null'::jsonb or r->'review'<>'null'::jsonb or r->>'submitted_at' is null then raise exception 'FAIL: release gate';end if;
 perform public.exam_api('submit',jsonb_build_object('id',eid));
 perform set_config('request.jwt.claim.sub',teacher::text,true);perform public.exam_api('release',jsonb_build_object('id',eid));
 perform set_config('request.jwt.claim.sub',s1::text,true);r:=public.exam_api('state',jsonb_build_object('id',eid));if (r->>'score')::numeric<>6 or (r->>'total')::numeric<>6 or jsonb_array_length(r->'review')<>2 then raise exception 'FAIL: server scoring';end if;
 r:=public.exam_api('save',jsonb_build_object('id',eid,'revision',2,'answers',jsonb_build_object(q1::text,1)));if (r->>'score')::numeric<>6 then raise exception 'FAIL: submitted answer changed';end if;
 perform set_config('request.jwt.claim.sub',teacher::text,true);r:=public.exam_api('create',jsonb_build_object('concept_id',cid,'request_id',gen_random_uuid(),'title','Deadline fixture test','question_count',1,'duration_minutes',5,'closes_at',now()+interval '1 day','student_ids',jsonb_build_array(s1)));timed:=(r->>'id')::uuid;
 perform set_config('request.jwt.claim.sub',s1::text,true);perform public.exam_api('start',jsonb_build_object('id',timed));
 execute 'reset role';update tipix_private.academic_exam_runs set deadline_at=clock_timestamp()-interval '1 second' where exam_id=timed;execute 'set local role authenticated';
 r:=public.exam_api('save',jsonb_build_object('id',timed,'revision',1,'answers',jsonb_build_object(q1::text,0)));if r->>'submitted_at' is null or r->'answers'<>'{}'::jsonb then raise exception 'FAIL: late answer accepted';end if;
 execute 'reset role';delete from tipix_private.academic_teacher_students where teacher_id=teacher;perform set_config('request.jwt.claim.sub',teacher::text,true);execute 'set local role authenticated';
 blocked:=false;begin perform public.exam_api('report',jsonb_build_object('id',eid));exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'FAIL: revoked teacher report';end if;
 execute 'reset role';if has_function_privilege('anon','public.exam_api(text,jsonb)','execute') then raise exception 'FAIL: anonymous API';end if;
end $$;
select 'passed' as exam_scoring_timing_and_authorization;
rollback;
