import {useState} from 'react';
import {supabase} from '../lib/supabase';
import MotionVisual from './MotionVisual';
import SetOperationsVisual from './SetOperationsVisual';
import type {LearningTask} from './learningApi';
export async function reviewAction<T>(op:string,payload:Record<string,unknown>):Promise<T>{const {data,error}=await supabase.rpc('curriculum_review',{op,payload});if(error)throw new Error(error.message);return data as T;}
type Inspection={books:{id:string;title:string;part:string;official_source_url:string;last_verified_at:string}[];concepts:{id:string;concept_title:string;subtopic:string;published:boolean;classification_reference:Record<string,unknown>;tasks:LearningTask[]}[]};
export default function CurriculumReview({id}:{id:string}){const[data,setData]=useState<Inspection|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function publishConcept(concept_id:string){setBusy(true);setError('');try{const{error}=await supabase.rpc('publish_learning_concept',{concept_id});if(error)throw error;await inspect();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 async function inspect(){setBusy(true);setError('');try{setData(await reviewAction('inspect',{curriculum_id:id}));}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <div><button className="w-button secondary" disabled={busy} onClick={()=>void inspect()}>{busy?'Opening…':'Review lessons and source'}</button>{error&&<p role="alert">{error}</p>}{data&&<section>{data.books.map(b=><p key={b.id}>{b.title} · Part {b.part} · source checked {new Date(b.last_verified_at).toLocaleDateString()} · <a href={b.official_source_url} target="_blank" rel="noreferrer">Official reference</a></p>)}<p className="w-note">Concept classifications and original lessons require your review. Publishing confirms your approval; it does not label original questions as NCERT questions.</p>{data.concepts.map(c=><details key={c.id} className="w-panel"><summary>{c.subtopic} → {c.concept_title} · {c.published?'Published':'Pending review'}</summary>{!c.published&&c.tasks.length>=7&&<button className="w-button" disabled={busy} onClick={()=>void publishConcept(c.id)}>Approve and publish this lesson</button>}{!c.tasks.length&&<p>Lesson content has not been authored yet.</p>}{c.tasks.map(t=><LessonEditor key={t.id} task={t} editable={!c.published}/>)}</details>)}</section>}</div>;
}
function LessonEditor({task,editable}:{task:LearningTask;editable:boolean}){const [blocks,setBlocks]=useState(task.blocks),[editing,setEditing]=useState(false),[json,setJson]=useState(JSON.stringify(task.blocks,null,2)),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 async function save(){setBusy(true);setStatus('');try{const b=JSON.parse(json);await reviewAction('save_task',{task_id:task.id,blocks:b});setBlocks(b);setEditing(false);setStatus('Draft saved.');}catch(e){setStatus(String(e));}finally{setBusy(false);}}
 return <article><h3>{task.position}. {task.title}</h3>{blocks.map((b,i)=><div key={i}>{b.type==='motion'?<MotionVisual/>:b.type==='venn'?<SetOperationsVisual/>:null}<p style={{whiteSpace:'pre-line'}}>{b.text}</p></div>)}{task.check_prompt&&<><p><strong>Mini check:</strong> {task.check_prompt}</p><ol>{task.check_options.map(x=><li key={x}>{x}</li>)}</ol></>}{editable&&<button className="w-text-button" onClick={()=>setEditing(!editing)}>Edit lesson blocks</button>}{editing&&<div className="ai-form"><label>Lesson blocks (JSON)<textarea rows={10} value={json} onChange={e=>setJson(e.target.value)}/></label><button className="w-button" disabled={busy} onClick={()=>void save()}>Save draft</button></div>}<p role="status">{status}</p></article>;
}
export function QuestionEditor({id,text,hint,answer,explanation,onSaved}:{id:string;text:string;hint?:string|null;answer:unknown;explanation:string;onSaved:()=>Promise<void>}){const[open,setOpen]=useState(false),[question,setQuestion]=useState(text),[tip,setTip]=useState(hint||''),[key,setKey]=useState(JSON.stringify(answer)),[solution,setSolution]=useState(explanation),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 async function save(){setBusy(true);try{await reviewAction('save_question',{question_id:id,question_text:question,hint:tip,answer:JSON.parse(key),explanation:solution});setStatus('Draft saved. Review before publication.');await onSaved();}catch(e){setStatus(String(e));}finally{setBusy(false);}}
 return <div><button className="w-text-button" onClick={()=>setOpen(!open)}>Edit draft question</button>{open&&<div className="ai-form"><label>Question<textarea value={question} onChange={e=>setQuestion(e.target.value)}/></label><label>Hint<input value={tip} onChange={e=>setTip(e.target.value)}/></label><label>Answer (JSON)<input value={key} onChange={e=>setKey(e.target.value)}/></label><label>Detailed solution<textarea rows={5} value={solution} onChange={e=>setSolution(e.target.value)}/></label><button className="w-button" disabled={busy} onClick={()=>void save()}>Save draft</button></div>}<p role="status">{status}</p></div>;
}
