import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {ArrowLeft,ArrowRight,ArrowUpRight,BookOpen,Check,Search} from 'lucide-react';
import {supabase} from '../lib/supabase';
import {useStudentProfile} from '../auth/AuthProvider';
import {useAcademic} from './AcademicContext';
import type {ReactNode} from 'react';
import './LearningJourney.css';
import './CurriculumBrowser.css';
export type CatalogConcept={id:string;title:string;topic_id:string|null;subtopic:string;position:number;lesson_available:boolean;question_count:number;mastery:number|null};
export type CatalogChapter={id:string;title:string;position:number;book_id:string|null;source_url:string;topics:{id:string;title:string;position:number}[];concepts:CatalogConcept[]};
export type CatalogSubject={id:string;subject:string;class_level:number;academic_year:string;board:string;in_study_plan:boolean;books:{id:string;title:string;part:string;source_url:string}[];chapters:CatalogChapter[]};
const subjectPath=(s:CatalogSubject)=>`/app/subjects/${encodeURIComponent(`${s.subject}::${s.academic_year}`)}`;
const chapterPath=(s:CatalogSubject,c:CatalogChapter)=>`/app/chapters/${encodeURIComponent(`${s.subject}::${s.academic_year}::${c.title}`)}`;
export function masteryRollup(concepts:CatalogConcept[]){return concepts.length?Math.round(concepts.reduce((sum,c)=>sum+(c.mastery??0),0)/concepts.length):0;}
function useCatalog(){
 const profile=useStudentProfile();const[data,setData]=useState<CatalogSubject[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let live=true;setLoading(true);setError('');void supabase.rpc('curriculum_catalog').then(({data,error})=>{if(!live)return;if(error)setError(error.message);else setData(data as CatalogSubject[]);setLoading(false);},()=>{if(live){setError('Unable to load your curriculum. Please try again.');setLoading(false);}});return()=>{live=false;};},[profile.id,profile.grade,retry]);
 return {data,loading,error,retry:()=>setRetry(x=>x+1)};
}
function CatalogBoundary({state,children}:{state:ReturnType<typeof useCatalog>;children:ReactNode}){return state.loading?<div className="lp-skeleton" role="status">Loading your course library…</div>:state.error?<section className="lp-empty" role="alert"><h2>Course library could not load</h2><p>{state.error}</p><button className="w-button" onClick={state.retry}>Try again</button></section>:<>{children}</>;}
function Progress({concepts}:{concepts:CatalogConcept[]}){const measured=concepts.filter(c=>c.mastery!==null).length;return <div className="cb-progress"><div><span>Practice mastery</span><strong>{masteryRollup(concepts)}%</strong></div><progress value={masteryRollup(concepts)} max={100}/><small>{measured} of {concepts.length} concepts assessed · unassessed concepts count as 0</small></div>;}
export function CurriculumCourses(){const catalog=useCatalog();const profile=useStudentProfile();const {overview}=useAcademic();const[search,setSearch]=useState('');const subjects=catalog.data.filter(s=>s.subject.toLowerCase().includes(search.trim().toLowerCase()));const recent=overview?.progress.find(p=>catalog.data.some(s=>s.chapters.some(h=>h.concepts.some(c=>c.id===p.concept_id&&c.lesson_available))));return <CatalogBoundary state={catalog}><div className="lj-heading"><span className="w-eyebrow">YOUR LEARNING LIBRARY · CLASS {profile.grade}</span><h1>Choose a subject.</h1><p>Your complete chapter library. Explore in any order.</p></div><div className="lp-library-tools"><label className="lp-search"><Search size={18}/><input aria-label="Search subjects" placeholder="Find a subject…" value={search} onChange={e=>setSearch(e.target.value)}/></label><span className="lp-pills"><span>Class {profile.grade}</span><span>{catalog.data[0]?.academic_year}</span></span></div>{recent&&<Link className="lp-resume" to={`/app/concepts/${recent.concept_id}`}><BookOpen size={22}/><div><small>CONTINUE LEARNING</small><strong>Return to your saved lesson</strong></div><ArrowRight size={20}/></Link>}<div className="lp-course-grid">{subjects.map(s=>{const concepts=s.chapters.flatMap(c=>c.concepts);return <article className="lp-course" key={s.id}><div className="lp-course-image"><BookOpen size={58}/><span>CLASS {s.class_level}</span></div><div className="lp-course-content"><span className="w-eyebrow">{s.academic_year} · {s.board}</span><h2>{s.subject}</h2><p>{s.books.length} {s.books.length===1?'book':'books'} · {concepts.length} concepts</p><div className="lp-course-count"><strong>{s.chapters.length}</strong><span>chapters · all available to browse</span></div><Progress concepts={concepts}/><small>{concepts.filter(c=>c.lesson_available).length} lessons ready{s.in_study_plan?'':' · outside your registered stream'}</small><Link to={subjectPath(s)}>Explore chapters <ArrowUpRight size={20}/></Link></div></article>})}</div>{!subjects.length&&<section className="lp-empty">{search?'No subjects match your search.':'Your class curriculum has not been added yet.'}</section>}<p className="lp-footnote">Lesson and question preparation is shown separately from the curriculum. <Link to="/app/syllabus">Syllabus references</Link></p></CatalogBoundary>;}
export function CurriculumSubject(){const {subject}=useParams();const catalog=useCatalog();const[search,setSearch]=useState('');const s=catalog.data.find(s=>`${s.subject}::${s.academic_year}`===subject);return <CatalogBoundary state={catalog}><Link className="lj-back" to="/app/courses"><ArrowLeft size={16}/> All subjects</Link>{s?<><div className="lj-heading"><span className="w-eyebrow">CLASS {s.class_level} · {s.academic_year} · {s.board}</span><h1>{s.subject}</h1><p>{s.chapters.length} chapters. Choose any chapter to explore its full learning map.</p></div><Progress concepts={s.chapters.flatMap(c=>c.concepts)}/><label className="lp-search"><Search size={18}/><input aria-label="Search chapters" placeholder="Search chapters…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="cb-chapters">{s.chapters.filter(c=>c.title.toLowerCase().includes(search.trim().toLowerCase())).map(c=><Link className="cb-chapter" key={c.id} to={chapterPath(s,c)}><span className="cb-number">{String(c.position).padStart(2,'0')}</span><div><span className="w-eyebrow">{s.books.find(b=>b.id===c.book_id)?.title||s.subject}</span><h2>{c.title}</h2><p>{c.topics.length} topics · {c.concepts.length} concepts</p><Progress concepts={c.concepts}/><span className="lp-status">{c.concepts.some(x=>x.lesson_available)?`${c.concepts.filter(x=>x.lesson_available).length} lessons ready`:'Lessons in preparation'}</span></div><ArrowRight size={20}/></Link>)}</div>{!s.chapters.some(c=>c.title.toLowerCase().includes(search.trim().toLowerCase()))&&<p role="status">No chapters match your search.</p>}</>:<section className="lp-empty">This subject is not in your class curriculum.</section>}</CatalogBoundary>;}
export function CurriculumChapter(){const {chapter}=useParams();const catalog=useCatalog();const s=catalog.data.find(s=>s.chapters.some(h=>`${s.subject}::${s.academic_year}::${h.title}`===chapter));const h=s?.chapters.find(h=>`${s.subject}::${s.academic_year}::${h.title}`===chapter);return <CatalogBoundary state={catalog}><Link className="lj-back" to={s?subjectPath(s):'/app/courses'}><ArrowLeft size={16}/> {s?.subject||'Courses'}</Link>{h&&s?<div className="lj-map"><aside className="lj-chapter-summary"><BookOpen size={34}/><span className="w-eyebrow">CLASS {s.class_level} · CHAPTER {h.position}</span><h1>{h.title}</h1><p>{h.topics.length} topics · {h.concepts.length} concepts</p><Progress concepts={h.concepts}/><p>All concepts are shown below. Prepared lessons open in TIPIX.</p><a href={h.source_url} target="_blank" rel="noreferrer">Official chapter reference <ArrowUpRight size={14}/></a><p className="lp-footnote">TIPIX topic and concept organisation is pending editorial review.</p></aside><div className="lj-topic-path">{[...h.topics,...(h.concepts.some(c=>!c.topic_id)?[{id:'',title:'Learning concepts',position:999}]:[])].map((t,i)=><section className="lj-topic" key={t.id}><div className="lj-topic-label"><span>{String(i+1).padStart(2,'0')}</span><h2>{t.title}</h2></div>{h.concepts.filter(c=>(c.topic_id||'')===t.id).map(c=><Link className="lj-concept-node" key={c.id} to={`/app/concepts/${c.id}`}><span className="lj-node-icon">{(c.mastery??0)>=80?<Check size={21}/>:<ArrowRight size={21}/>}</span><div><small>{c.lesson_available?'LEARN & PRACTISE':'CONTENT IN PREPARATION'}</small><h3>{c.title}</h3><p>{c.mastery===null?'No assessed mastery yet':`${c.mastery}% practice mastery`}{c.question_count>0?` · ${c.question_count} questions`:''}</p></div><ArrowUpRight size={20}/></Link>)}</section>)}</div></div>:<section className="lp-empty">This chapter is not in your class curriculum.</section>}</CatalogBoundary>;}
export function PreparingConcept({id}:{id:string}){const catalog=useCatalog();const s=catalog.data.find(s=>s.chapters.some(h=>h.concepts.some(c=>c.id===id)));const h=s?.chapters.find(h=>h.concepts.some(c=>c.id===id));const c=h?.concepts.find(c=>c.id===id);return <CatalogBoundary state={catalog}><Link className="lj-back" to={s&&h?chapterPath(s,h):'/app/courses'}><ArrowLeft size={16}/> Back to {h?'chapter':'courses'}</Link><div className="lj-heading"><span className="w-eyebrow">{s?.subject} · {h?.title}</span><h1>{c?.title||'Concept unavailable'}</h1></div><section className="lp-empty"><h2>{s&&!s.in_study_plan?'Outside your registered stream':'Lesson in preparation'}</h2><p>{s&&!s.in_study_plan?'You can browse this curriculum. Learning activities follow your registered class and stream.':'This concept is part of your course map. Its explanation, examples and practice will appear here once reviewed.'}</p><Link className="w-button" to={s&&h?chapterPath(s,h):'/app/courses'}>Explore other concepts <ArrowRight size={16}/></Link></section></CatalogBoundary>;}
