import {useState} from 'react';
import './FoundationExplorer.css';
/** Small interactive teaching tools. Values are illustrative, never student analytics. */
export default function FoundationExplorer({kind}:{kind:string}){
 const [value,setValue]=useState(36);const [selected,setSelected]=useState(0);
 const ranks=['Species','Genus','Family','Order','Class','Phylum / Division','Kingdom'];
 if(kind==='units')return <section className="foundation-explorer"><span className="w-eyebrow">EXPLORE · SAME SPEED, DIFFERENT UNITS</span><label>Speed: {value} km/h<input type="range" min="0" max="180" step="9" value={value} onChange={e=>setValue(Number(e.target.value))}/></label><div className="fe-equation"><strong>{value} <small>km/h</small></strong><span>× 1000 ÷ 3600</span><strong>{(value/3.6).toFixed(1)} <small>m/s</small></strong></div><p>The physical speed stays the same. Only its numerical representation changes.</p></section>;
 if(kind==='mole')return <section className="foundation-explorer"><span className="w-eyebrow">EXPLORE · COUNTING WATER MOLECULES</span><label>Water mass: {value} g<input type="range" min="0" max="180" step="9" value={value} onChange={e=>setValue(Number(e.target.value))}/></label><div className="fe-equation"><strong>{value} g</strong><span>÷ 18 g/mol</span><strong>{(value/18).toFixed(2)} mol</strong></div><p>Using rounded M(H₂O) = 18 g/mol, this corresponds to {(value/18*6.02214076).toFixed(3)} × 10²³ molecules. The sample contains twice as many hydrogen atoms as water molecules.</p></section>;
 if(kind==='taxonomy')return <section className="foundation-explorer"><span className="w-eyebrow">EXPLORE · NARROW TO BROAD</span><div className="fe-ranks" role="group" aria-label="Taxonomic ranks">{ranks.map((r,i)=><button key={r} className={selected===i?'active':''} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{i+1}. {r}</button>)}</div><p role="status"><strong>{ranks[selected]}</strong>{selected===0?' is the narrowest rank in this sequence. A genus can contain several species.':` contains groups from the narrower ${ranks[selected-1].toLowerCase()} rank.`} {selected<6?`The next broader rank is ${ranks[selected+1].toLowerCase()}.`:'Kingdom is the broadest rank displayed here.'}</p></section>;
 if(kind==='mapping'){const input=selected-2;return <section className="foundation-explorer"><span className="w-eyebrow">EXPLORE · A FUNCTION IS A RELATION</span><p>Domain A = {'{−2, −1, 0, 1, 2}'}. Rule f(x) = x². Choose an input.</p><div className="fe-ranks" role="group" aria-label="Function inputs">{[-2,-1,0,1,2].map((n,i)=><button key={n} aria-pressed={selected===i} className={selected===i?'active':''} onClick={()=>setSelected(i)}>{n}</button>)}</div><div className="fe-equation" aria-live="polite"><strong>{input}</strong><span>square the input</span><strong>{input*input}</strong></div><p>Ordered pair: ({input}, {input*input}). Try both −2 and 2: different inputs can share an output. Range = {'{0, 1, 4}'}.</p></section>;}
 const cases=[['Seedling','Its cells use nutrients and energy, grow through cell division and respond to conditions. These features work together in a living system.'],['Salt crystal','It may grow by deposition, but lacks cellular metabolism. Growth alone is not enough to classify it as living.'],['Moving toy','A motor produces movement. Motion alone does not imply the presence of cells or biological metabolism.']];
 return <section className="foundation-explorer"><span className="w-eyebrow">COMPARE THE EVIDENCE</span><div className="fe-ranks" role="group" aria-label="Examples of living and non-living systems">{cases.map((c,i)=><button key={c[0]} aria-pressed={selected===i} className={selected===i?'active':''} onClick={()=>setSelected(i)}>{c[0]}</button>)}</div><p role="status" key={selected}>{cases[selected][1]}</p></section>;
}
