import {useEffect,useRef,useState} from 'react';
import {ArrowRight,CheckCircle2} from 'lucide-react';
import {useAcademic} from './AcademicContext';
import {academic,type Question,type Feedback} from './api';
import {learning,type LearningState} from './learningApi';
type Metadata={source_id:string;source_name:string;year:number|null;difficulty:number;type:string};
type Result={question:Question|null;metadata:Metadata[];total:number;answered:number;state:LearningState|null};
export default function InlinePractice({conceptId,group=''}:{conceptId:string;group?:string}){
 const{refresh}=useAcademic();const[r,setR]=useState<Result|null>(null),[filters,setFilters]=useState<Record<string,string>>({group}),[answer,setAnswer]=useState<unknown>(''),[feedback,setFeedback]=useState<Feedback|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[save,setSave]=useState('');const request=useRef(crypto.randomUUID()),generation=useRef(0),answerRef=useRef<unknown>(''),queue=useRef(Promise.resolve()),lock=useRef(false);
 async function load(f=filters){const g=++generation.current;setLoading(true);setError('');setFeedback(null);request.current=crypto.randomUUID();try{await queue.current;const data=await learning<Result>('next',{concept_id:conceptId,filters:f});if(g!==generation.current)return;setR(data);const draft=data.state?.question_id===data.question?.id?data.state?.draft:'';setAnswer(draft??'');answerRef.current=draft??'';setSave(data.state?.question_id===data.question?.id?'Saved answer restored':'');}catch(e){if(g===generation.current)setError(String(e));}finally{if(g===generation.current)setLoading(false);}}
 useEffect(()=>{let active=true;learning<{state:LearningState|null}>('lesson',{concept_id:conceptId}).then(d=>{if(!active)return;const f={...(d.state?.filters||{}),group};setFilters(f);void load(f);}).catch(e=>{if(active){setError(String(e));setLoading(false);}});return()=>{active=false;generation.current++;};},[conceptId,group]);
 function changeAnswer(value:unknown){setAnswer(value);answerRef.current=value;setSave('Saving…');const qid=r?.question?.id;if(!qid)return;queue.current=queue.current.catch(()=>{}).then(async()=>{await learning('draft',{concept_id:conceptId,question_id:qid,answer:value,filters});setSave('Saved');}).catch(e=>{setSave('Not saved');setError(String(e));throw e;});void queue.current.catch(()=>{});}
 async function submit(){if(!r?.question||lock.current)return;lock.current=true;setBusy(true);setError('');try{await queue.current.catch(()=>{});const feedback=await academic<Feedback>('submit',{question_id:r.question.id,request_id:request.current,answer:answerRef.current,response_time_ms:0});setFeedback(feedback);setSave('Answer submitted');await refresh();}catch(e){setError(String(e));}finally{lock.current=false;setBusy(false);}}
 const q=r?.question;function answerLabel(a:unknown){if(typeof a==='number'&&q&&['mcq','assertion_reason'].includes(q.question_type))return q.options[a];if(Array.isArray(a))return a.map(x=>q?.options[Number(x)]).join(', ');return String(a);}
 return <div className="lp-practice"><div className="lp-filter-row">{(['source','difficulty','year','type'] as const).map(key=>{const options=key==='source'?Array.from(new Map(r?.metadata.map(m=>[m.source_id,m.source_name])).entries()):Array.from(new Set(r?.metadata.map(m=>key==='year'?m.year:key==='type'?m.type:m.difficulty).filter(v=>v!==null))).sort().map(v=>[String(v),key==='difficulty'?['','Easy','Medium','Hard'][Number(v)]:String(v).replaceAll('_',' ')]);return <label key={key}>{key}<select value={filters[key]||''} disabled={busy||loading} onChange={e=>{const f={...filters,[key]:e.target.value};setFilters(f);queue.current=queue.current.catch(()=>{}).then(async()=>{await learning('filters',{concept_id:conceptId,filters:f});}).catch(e=>{setError(String(e));throw e;});void load(f);}}><option value="">All {key==='difficulty'?'levels':key==='type'?'types':`${key}s`}</option>{options.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>;})}</div>
 {error&&<div role="alert"><p>{error}</p><button className="w-button secondary" onClick={()=>void load()}>Try again</button></div>}
 {loading?<div className="lp-skeleton" role="status">Loading concept questions…</div>:q?<><div className="lp-pills"><span>{q.source_name}</span>{q.source_year&&<span>{q.source_year}</span>}<span>{['','Easy','Medium','Hard'][q.difficulty]}</span><span>{q.marks} marks</span></div><p className="lp-meta">{r?.answered} answered · {r?.total} available in this concept</p><h3>{q.question_text}</h3><fieldset disabled={busy||!!feedback}><legend>Your answer</legend>{['mcq','assertion_reason','multiple_select','true_false'].includes(q.question_type)?(q.question_type==='true_false'?['True','False']:q.options).map((option,i)=>{const v=q.question_type==='true_false'?i===0:i;const multi=q.question_type==='multiple_select';return <label className="lp-option" key={i}><input type={multi?'checkbox':'radio'} name={`question-${q.id}`} checked={multi?Array.isArray(answer)&&answer.includes(i):answer===v} onChange={()=>changeAnswer(multi?(Array.isArray(answer)&&answer.includes(i)?answer.filter(x=>x!==i):[...(Array.isArray(answer)?answer:[]),i]):v)}/><span>{option}</span></label>}):<input aria-label="Your answer" type={q.question_type==='numerical'?'number':'text'} step="any" value={String(answer??'')} onChange={e=>changeAnswer(q.question_type==='numerical'&&e.target.value!==''?Number(e.target.value):e.target.value)}/>}</fieldset>
 {feedback?<div className="lp-feedback" role="status"><CheckCircle2 size={20}/><h3>{feedback.attempt.correct?'Correct':'Let’s work through this'}</h3><p><strong>Correct answer: {answerLabel(feedback.answer)}</strong></p><p>{feedback.explanation}</p>{!feedback.attempt.correct&&<p>Compare your steps with this explanation, then revisit the key idea above before trying a similar question.</p>}<p>{feedback.attempt.marks_earned}/{feedback.attempt.marks_available} marks · {feedback.attempt.points} points saved</p><button className="w-button" onClick={()=>void load()}>Next question <ArrowRight size={16}/></button></div>:<button className="w-button" disabled={busy||answer===''||(Array.isArray(answer)&&!answer.length)} onClick={()=>void submit()}>{busy?'Checking…':'Check answer'}</button>}<span className="lp-save" role="status">{save}</span></>:!error?<div className="lp-empty"><h3>{group==='pyq'?'Previous-year questions':group==='ncert'?'NCERT / textbook questions':'Concept practice'}</h3><p>{r?.total?'No unanswered questions match these filters.':'No verified '+(group==='pyq'?'previous-year ':'')+'questions are currently available for this concept.'}</p><p>New questions appear here after source and answer review.</p></div>:null}</div>;
}
