import {useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,BookOpen,Search,GraduationCap} from 'lucide-react';
import {useStudentProfile} from '../auth/AuthProvider';
import {useAcademic} from './AcademicContext';
import {DataBoundary} from './AcademicPages';
import './ContentStudio.css';
const base='https://cbseacademic.nic.in/web_material/CurriculumMain27/';
const textbook='https://ncert.nic.in/textbook.php';
const sources:Record<string,string>={Mathematics:'Maths',Physics:'Physics',Chemistry:'Chemistry',Biology:'Biology',Accountancy:'Accountancy','Business Studies':'BusinessStudies',Economics:'Economics'};
export function syllabusSubjects(grade:number,stream:string){return grade<=10?['Mathematics','Science']:stream==='commerce'?['Accountancy','Business Studies','Economics','Mathematics']:stream==='pcb'?['Physics','Chemistry','Biology']:stream==='pcmb'?['Physics','Chemistry','Mathematics','Biology']:['Physics','Chemistry','Mathematics'];}
export function syllabusUrl(grade:number,subject:string){if(grade<=8)return textbook;if(grade===9)return base+'SecPart1/'+(subject==='Mathematics'?'Maths_SecP1IX':'ScienceSt_SecP1')+'_2026-27.pdf';if(grade===10)return base+'SecPart1/'+(subject==='Mathematics'?'Maths_SecP1X':'Science_SecP1')+'_2026-27.pdf';return base+'SecPart2/'+sources[subject]+'_SecP2_2026-27.pdf';}
export default function Syllabus(){const profile=useStudentProfile();const{concepts}=useAcademic();const[search,setSearch]=useState('');const grade=Number(profile.grade);const subjects=syllabusSubjects(grade,profile.stream||'').filter(s=>s.toLowerCase().includes(search.toLowerCase()));return <DataBoundary><div className="lj-heading"><span className="w-eyebrow">CLASS {grade} · 2026–27</span><h1>Your syllabus, in one place.</h1><p>Read the official curriculum and see which lessons are available in TIPIX.</p></div><label className="cs-search"><Search size={19}/><span className="sr-only">Find a subject</span><input placeholder="Find a subject…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="cs-subject-grid">{subjects.map((subject,i)=>{const published=concepts.filter(c=>c.subject===subject);const chapters=new Set(published.map(c=>c.chapter_title)).size;return <article className="cs-subject" key={subject} style={{animationDelay:`${i*60}ms`}}><div className="cs-subject-top"><BookOpen size={25}/><span className="w-tag">{grade<=8?'NCERT textbooks':'CBSE curriculum'}</span></div><h2>{subject}</h2><p>{grade<=8?'Choose your class, subject and book in the official NCERT catalogue.':'Complete official 2026–27 subject syllabus, including assessment requirements.'}</p><a className="w-button secondary" href={syllabusUrl(grade,subject)} target="_blank" rel="noreferrer">{grade<=8?'Open textbook catalogue':'Read full official syllabus'} <ArrowUpRight size={17}/></a><div className="cs-subject-status"><strong>{chapters} published {chapters===1?'chapter':'chapters'}</strong><span>{published.length} concepts · {published.reduce((n,c)=>n+c.question_count,0)} scored questions</span></div>{published.length>0?<Link to="/app/courses">Continue in TIPIX <ArrowUpRight size={15}/></Link>:<small>TIPIX lessons and question mapping are awaiting review.</small>}</article>;})}</div>{!subjects.length&&<p>No subjects match your search.</p>}<div className="lj-bottom"><GraduationCap size={22}/><p>Your registered class controls your learning plan. Official documents are references; they do not mean every lesson or question is available inside TIPIX.</p></div><a href="https://cbseacademic.nic.in/curriculum_2027.html" target="_blank" rel="noreferrer">Browse the full CBSE curriculum directory</a><p className="w-note">Sources checked 16 September 2026. For Classes 6–8 use the current textbook edition specified by your school. Commerce students should confirm whether Mathematics is part of their school subject selection.</p></DataBoundary>;}
