-- Original TIPIX explanatory prose, aligned to the six previously verified curriculum topics.
-- No publisher text or examination questions are reproduced.
update public.academic_concepts c set lesson=v.lesson,lesson_rights_reference='TIPIX-authored explanatory lesson, 2026-09-16; not reproduced NCERT text.'
from (values
('Reflexive Relations',E'A relation describes which ordered pairs belong together. A relation R on a set A is reflexive when every element is related to itself.\n\nRule: for every a in A, (a, a) belongs to R.\n\nVisual idea: draw one dot for each element. Every dot must have an arrow returning to itself. Arrows between different dots are allowed but do not replace a missing self-arrow.\n\nExample: on A = {1, 2}, the relation {(1, 1), (2, 2), (1, 2)} is reflexive. Removing (2, 2) makes it non-reflexive.\n\nCommon misconception: one self-pair is enough. Check every element in the underlying set, including elements that do not appear elsewhere in the relation.\n\nRecap: list the elements of A, then check that each required self-pair appears.'),
('Symmetric Relations',E'A relation is symmetric when every arrow between two elements has a matching arrow in the reverse direction.\n\nRule: whenever (a, b) belongs to R, (b, a) must also belong to R.\n\nExample: {(1, 2), (2, 1)} on {1, 2} is symmetric even though it is not reflexive. A self-pair already matches its own reverse.\n\nCommon misconception: symmetric means that all possible pairs must appear. Only pairs already present require their reverses.\n\nRecap: reverse each listed ordered pair and look for that reverse in the relation.'),
('Transitive Relations',E'Transitivity connects two consecutive relationships. When a relates to b and b relates to c, a must relate to c.\n\nRule: (a, b) in R and (b, c) in R imply (a, c) in R.\n\nVisual idea: follow any two-arrow path. There must also be a direct arrow from its starting point to its ending point. The starting and ending points may be the same.\n\nExample: {(1, 2), (2, 3)} is not transitive because (1, 3) is missing. Adding (1, 3) makes this particular relation transitive.\n\nCommon misconception: checking only three different elements. Paths returning to the same element also matter.\n\nRecap: inspect every composable pair of arrows, not just the most obvious chain.'),
('Equivalence Relations',E'An equivalence relation groups elements that are equivalent under a chosen rule. It must be reflexive, symmetric and transitive at the same time.\n\nExample: on the integers, relate a and b when a − b is even. Each integer relates to itself because the difference is zero. Reversing the order keeps the difference even. Adding two even differences shows transitivity.\n\nThis relation creates two groups: even integers and odd integers. These groups are equivalence classes. They do not overlap, and together they cover the set.\n\nCommon misconception: proving two properties is enough. All three are required.\n\nRecap: check self-pairs, reversed pairs and two-step chains separately before concluding that a relation is an equivalence relation.'),
('One-One Functions',E'A function is one-one, or injective, when different inputs always give different outputs.\n\nRule: f(a) = f(b) implies a = b.\n\nExample: f(x) = 3x + 2 on the real numbers is one-one: 3a + 2 = 3b + 2 forces a = b. In contrast, f(x) = x² on the real numbers is not one-one because 2 and −2 have the same output.\n\nDomain matters: x² becomes one-one when its domain is restricted to nonnegative real numbers.\n\nCommon misconception: each input having one output makes a function one-one. That is required of every function; injectivity instead prevents different inputs from sharing an output.\n\nRecap: look for two distinct inputs with equal outputs, or prove that equality of outputs forces equality of inputs.'),
('Onto Functions',E'A function is onto, or surjective, when every element of its stated codomain is reached by at least one input.\n\nRule: for each y in the codomain, there exists x in the domain with f(x) = y.\n\nExample: f(x) = x² from the real numbers to the real numbers is not onto: negative outputs are never reached. The same rule from the real numbers to the nonnegative real numbers is onto.\n\nVisual idea: every dot on the codomain side of an arrow diagram must receive at least one arrow. Several arrows may arrive at the same dot.\n\nCommon misconception: ignoring the codomain. Onto is a property of the complete function, including its domain and codomain.\n\nRecap: choose an arbitrary codomain value y and check whether an allowed input can produce it.')
)v(title,lesson),public.academic_curriculum_versions cv
where c.curriculum_id=cv.id and cv.board='CBSE' and cv.academic_year='2026-27' and cv.class_level=12 and cv.subject='Mathematics' and c.chapter_title='Relations and Functions' and c.concept_title=v.title and c.lesson is null;
